### ISSUE TITLE
一个平易近人的GitHub入门 

### ISSUE THREAD

**Issue by ontouchstart** [bigdata-mindstorms/jekyll-playground#14]
### [一个平易近人的GitHub入门 ](http://bigdata-mindstorms.github.io/jekyll-playground/public/VeroniqueSoleil/2016/04/02/GitHub.html)

by @VeroniqueSoleil 

- [source](https://github.com/bigdata-mindstorms/jekyll-playground/tree/gh-pages/public/VeroniqueSoleil/2016/04/02)

欢迎大家在这里讨论分享经验。

**Comment by LivingProgram** [comment]
文章能不能翻译成英文呢？如果没有人想做，我可以翻译。

**Comment by VeroniqueSoleil** [comment]
我翻译你审译吧，把Chinglish 改成English:joy:

# The Shortest Introduction of GitHub
As a noob and arts student, I deeply understand the confusion when read some articles filled with computer terms. Thus, I will try to use some easy words to explain GitHub. This is more than an introduction, but my own understanding of GitHub. I hope all of you, people who want to get into this field, can easily understand what you will learn and move forward without hesitation.

Before I start, I would like to recommend some articles:
（看看国外有什么好的关于GitHub入门的文章）

## What's GitHub

To begin with, I'm glad to refer you to the slogan of GitHub: **social coding**. This means everyone can participate in coding activities. So, compare to Git, GitHub breaches the walls between us and the programmers, giving the public opportunities to understand and take part in coding-- this is meaningful, because it not only helps programmers work out more user-friendly apps, but also lets other participants find their potentials.

I try to use some simple analogies to explain GitHub: **This is a website contains the functions of Git, "B", "C" and "D"**（列举国外流行的相同性质的网站）, and I want to divide these analogies into 4 points:

* Git: This is a platform used by programmers. Derive from Git, GitHub absolutely contains Git's functions (if you know nothing about code, this can be put aside)

* B: Apart from programmers storing their codes here, you can upload and store your files in GitHub

* C: People can discuss and communicate in the "issue" part of GitHub (I advise you learn Markdown syntax)

* D: Here I'd like to return to the relation between Git and GitHub. In the form of website, GitHub contains all the functions of Git, so people can write their file without learning Git language. That is to say, the glass between Git and the public is broken

So, it is easier for newbies to learn GitHub.

## Why use GitHub
Whether you finally get into this field or not, you should learn and use GitHub:

* Safety: There's no place safer than a place that used by millions of programmers

* Big Storage Volume: You can store files here as many as you want

* Simplicity: No advertisement will bother you

* Fresh Experience: Using GitHub can bring you fresh experience. Moreover, you can meet programmers all over the world and see their public files

## How to use GitHub
* First, you should get a GitHub account, please click here

* After getting an account, you can create your own repositpries and then write, upload files; you can also establish your organizations

* May be you will be members of several organizations and participate in various programs: write and upload you files in "code" part and discuss with people in "issue" part

**When start your exploration, you may be ill at ease, but don't be afraid, because every veteran has a clumsy beginning.**

**Comment by LivingProgram** [comment]
@VeroniqueSoleil 
What is a "noob and arts student"?

**Comment by LivingProgram** [comment]
# The Shortest Introduction of GitHub
As a noob and arts student, I deeply understand the confusion when reading some articles filled with computer terms. Thus, I will try to use some easy words to explain GitHub. This is more than an introduction, but my own understanding of GitHub. I hope anyone that wants to enter into this field can easily understand what you will learn and move forward without hesitation.

Before I start, I would like to recommend some articles:
（看看国外有什么好的关于GitHub入门的文章）

## What's GitHub

To begin with, I'm glad to refer you to the slogan of GitHub: **social coding**. This means everyone can participate in coding activities. So, compared to Git, GitHub breaches the walls between us and the programmers, giving the public opportunities to understand and take part in coding-- this is meaningful, because it not only helps programmers work out more user-friendly apps, but also lets other participants find their potentials.

I try to use some simple analogies to explain GitHub: **This is a website contains the functions of Git, "B", "C" and "D"**（列举国外流行的相同性质的网站）, and I want to divide these analogies into 4 points:

* Git: This is a platform used by programmers. Derive from Git, GitHub absolutely contains Git's functions (if you know nothing about code, this can be put aside)

* B: Apart from programmers storing their codes here, you can upload and store your files in GitHub

* C: People can discuss and communicate in the "issue" part of GitHub (I advise you learn Markdown syntax)

* D: Here I'd like to return to the relation between Git and GitHub. In the form of website, GitHub contains all the functions of Git, so people can write their file without learning Git language. That is to say, the glass between Git and the public is broken

So, it is easier for newbies to learn GitHub.

## Why use GitHub
Whether you finally get into this field or not, you should learn and use GitHub:

* Safety: There's no place safer than a place that used by millions of programmers

* Big Storage Volume: You can store as many files here as you want

* Simplicity: No advertisement will bother you

* Fresh Experience: Using GitHub can bring you fresh experience. Moreover, you can meet programmers all over the world and see their public files

## How to use GitHub
* First, you should get a GitHub account, please click here

* After getting an account, you can create your own repositories, then write and upload files; you can also establish your organizations

* You might be members of several organizations and participate in various programs: so you can write and upload your files in "code" part and discuss with people in the "issue" part

**When you start your exploration, you may be ill at ease, but don't be afraid, because every veteran has a clumsy beginning.**

**Comment by VeroniqueSoleil** [comment]
@LivingProgram
 **noob**：菜鸟
 **arts student**：文科生
Look like they don't make sense...how about "newbie" and “student of arts”?

**Comment by LivingProgram** [comment]
Yes, that would be great! :+1:
